pro TEST_GET_VIIRS_DATE_INFO

; LIKE A UNIT TEST FOR GET_VIIRS_LAT_LON

; READ IN THE TEST FILE AND PRINT THE LAT AND LON TO THE SCREEN
CD, CURRENT=c
VIIRS_TEST_FILE = c + '/Source/viirs/test/' + 'NPP_VMAE_L1.A2013176.0030.P1_03001.2013176093155.hdf'
DATE_INFO = GET_VIIRS_DATE_INFO(VIIRS_TEST_FILE)
 ;; 2013-06-25 00:30:17.30
;;IF KEYWORD_SET(VERBOSE) THEN PRINT, 'MODISA DATE INFO: DEFINING DATE_INFO STRUCTURE'
IF DATE_INFO.YEAR  EQ 2013 THEN PRINT, 'YEAR TEST PASSED'
IF DATE_INFO.MONTH EQ 6 THEN PRINT, 'MONTH TEST PASSED'
IF DATE_INFO.DAY   EQ 25 THEN PRINT, 'DAY TEST PASSED'

END
