PRO TEST_GET_VIIRS_VIEWING_GEOMETRIES

; LIKE A UNIT TEST FOR GET_VIIRS_VIEWING_GEOMETRIES

CD, CURRENT=c
VIIRS_TEST_FILE = c + '/Source/viirs/test/' + 'NPP_VMAE_L1.A2013176.0030.P1_03001.2013176093155.hdf'
VIEW_INFO = GET_VIIRS_VIEWING_GEOMETRIES(VIIRS_TEST_FILE)

PRINT, VIEW_INFO.SZA[0,0]
PRINT, VIEW_INFO.SAA[0,0]
PRINT, VIEW_INFO.VZA[0,0]
PRINT, VIEW_INFO.VAA[0,0]

IF VIEW_INFO.SZA[0,0] EQ 94.62213 THEN BEGIN
  PRINT, 'SZA Test passed'
ENDIF ELSE BEGIN
  print, 'SZA TEST FAILED'
ENDELSE

IF VIEW_INFO.SAA[0,0] EQ -54.248047 THEN BEGIN
  PRINT, 'SAA Test passed'
ENDIF ELSE BEGIN
  print, 'SAA TEST FAILED'
ENDELSE

IF VIEW_INFO.VZA[0,0] EQ 70.5284 THEN BEGIN
  PRINT, 'VZA Test passed'
ENDIF ELSE BEGIN
  print, 'VZA TEST FAILED'
ENDELSE

IF VIEW_INFO.VAA[0,0] EQ -129.55676 THEN BEGIN
  PRINT, 'VAA Test passed'
ENDIF ELSE BEGIN
  print, 'VAA TEST FAILED'
ENDELSE



END