PRO TEST_GET_VIIRS_EMISSIVE_BTEMP

; LIKE A UNIT TEST FOR GET_VIIRS_BTEMP

; READ IN THE TEST FILE AND PRINT THE LAT AND LON TO THE SCREEN
;/home/marrabld/projects/DIMITRI_2.0/Source/viirs/test
CD, CURRENT=c
VIIRS_TEST_FILE = c + '/Source/viirs/test/' + 'NPP_VMAE_L1.A2013176.0030.P1_03001.2013176093155.hdf'
BTEMP = GET_VIIRS_EMISSIVE_BTEMP(VIIRS_TEST_FILE)
PRINT, BTEMP[0,0,0]
END