PRO MERGE_DIMITRI_DATABASE

; THIS PROGRAM LOADS TWO DIMITRI DATABASE FILE 
; AND TRANSFERS THE MANUAL CLOUD SCREENING 
; FROM ONE VERSION TO THE OTHER

; NOTE, PLEASE RUN THE @COMPILE_DIMITRI COMMAND 
; IN THE DIMITRI FOLDER LOCATION OF DATABASE2 
; (THE ONE TO BE UPDATED) AND STAY IN THE SOURCE DIRECTORY

; DEFINE BOTH DATABASE FILES

;  DB1_FILE = 'C:\Documents and Settings\Christopher\Desktop\db_copy_11_August_2011\DIMITRI_DATABASE.CSV'
;  DB2_FILE = 'C:\Documents and Settings\Christopher\Desktop\db_copy_11_August_2011\ 1_Aug_2011_DIMITRI_DATABASE.CSV'

  restore,'./validation/db1_data_new_format_20120410.sav'


; READ IN BOTH DATABASES

  DB_TEMPLATE  = GET_DIMITRI_TEMPLATE(1,/TEMPLATE,VERBOSE=VERBOSE)
 ; DB1_DATA     = READ_ASCII(DB1_FILE,TEMPLATE=DB_TEMPLATE)
  DB2_DATA     = READ_ASCII(get_dimitri_location('DATABASE'),TEMPLATE=DB_TEMPLATE)
  COUNTER      = 0l

; FIND INDEX OF ALL CHANGES TO MANUAL CS IN DB1

  CHID = WHERE(DB1_DATA.MANUAL_CS NE -1 and DB1_DATA.sensor eq 'VEGETATION', COUNT)
  IF COUNT EQ 0 THEN GOTO, NO_CHANGE

; LOOP OVER EACH INDEX VALUE

  FOR II=0L,COUNT-1 DO BEGIN
  print, ii, ' out of ',count-1 

   ; if ii mod count/10. eq 0 then print, string(string(float(ii)/float(count),format='(i3)')+'% complete...')

    MATCH = WHERE(DB2_DATA.FILENAME EQ DB1_DATA.FILENAME[CHID[II]]  AND $
                  DB2_DATA.REGION EQ DB1_DATA.REGION[CHID[II]]      AND $
                  DB2_DATA.SENSOR EQ DB1_DATA.SENSOR[CHID[II]]      AND $
                  DB2_DATA.PROCESSING_VERSION EQ DB1_DATA.PROCESSING_VERSION[CHID[II]],MCOUNT)
  
    IF MCOUNT EQ 0 THEN CONTINUE
    IF MCOUNT GT 1 THEN BEGIN
      PRINT, 'ERROR FOUND TWO MATCHES FOR FILENAME: ',DB2_DATA.FILENAME[CHID[II]]
      CONTINUE
    ENDIF

; CHANGE DB2 VALUE
  
    DB2_DATA.MANUAL_CS[MATCH] = DB1_DATA.MANUAL_CS[CHID[II]]
    COUNTER++

; END LOOP
  
  ENDFOR

;SAVE DB2
  
  RES = SAVE_DIMITRI_DATABASE(DB2_DATA)
  NO_CHANGE:
  PRINT, COUNTER, ' CHANGES MADE'

END