PRO STATISTICAL_CLOUD_SCREENING
; STATISTICALLY SCREEN DATA USING A THRESHOLD ON THE STDDEV VALUES

  SENSOR  = 'ATSR2'
  PROCVR  = 'Reprocessing_2008'
  SITES   = ['Amazon','BOUSSOLE','DomeC','Libya4','SIO','SPG','TuzGolu','Uyuni']
  BIDX    = 7 ;REMEMBER TO INCLUDE REFLEACTANCE AND STDEV INDEXS; STARTS FROM 0, 15 FOR MERIS WOULD BE STDEV OF 412NM
  THRESH  = 0.01

;--------------------------
; RESTORE DATABASE
  
  DB_TEMPLATE  = GET_DIMITRI_TEMPLATE(1,/TEMPLATE)
  DB_DATA      = READ_ASCII(GET_DIMITRI_LOCATION('DATABASE'),TEMPLATE=DB_TEMPLATE)
  IFOLDER      = GET_DIMITRI_LOCATION('INPUT')
  DL           = PATH_SEP()

  FOR II=0,N_ELEMENTS(SITES)-1 DO BEGIN

;--------------------------  
; RESTORE TIME SERIES DATA
    
    TEMP = IFOLDER+DL+'Site_'+SITES[II]+DL+SENSOR+DL+'Proc_'+PROCVR+DL+SENSOR+'_TOA_REF.dat'
    IF FILE_TEST(TEMP) EQ 0 THEN CONTINUE
    RESTORE,TEMP

;-------------------------- 
; FIND DATES WHERE ROI COVERED, 
; MAN_CS IS NOT DEFINED

    RES = WHERE(  DB_DATA.REGION EQ SITES[II] AND $
                  DB_DATA.SENSOR EQ SENSOR AND $
                  DB_DATA.PROCESSING_VERSION EQ PROCVR AND $
                  DB_DATA.ROI_COVER EQ 1 AND $
                  DB_DATA.MANUAL_CS LT 0,COUNT)
    IF COUNT EQ 0 THEN CONTINUE

;--------------------------
; LOOP OVER EACH DATE

    FOR JJ=0L,COUNT-1 DO BEGIN
    PRINT, JJ, ' OUT OF ',COUNT
    
    ;A = REBIN(ABS(SENSOR_L1B_REF[0,*]-DB_DATA.DECIMAL_YEAR[RES[JJ]]),N_ELEMENTS(SENSOR_L1B_REF[0,*])
      TT = WHERE(ABS(SENSOR_L1B_REF[0,*]-DB_DATA.DECIMAL_YEAR[RES[JJ]]) LT 0.00005D,RES2)
      IF RES2 LT 1 THEN STOP
      TT2 = WHERE(SENSOR_L1B_REF[5+12+BIDX,TT] LT THRESH,AA)
      IF AA GT 0 THEN DB_DATA.MANUAL_CS[RES[JJ]]=0
    ENDFOR

;--------------------------
; SORT OUT NETCDFS

    RES = WHERE(DB_DATA.REGION EQ SITES[II] AND $
                DB_DATA.SENSOR EQ SENSOR AND $
                DB_DATA.PROCESSING_VERSION EQ PROCVR,COUNT)
    IF COUNT  GT 0 THEN BEGIN     
    
      NEWVAR = DB_DATA.MANUAL_CS[RES]
      REL = UPDATE_DIMITRI_EXTRACT_TOA_NCDF(SITES[II],SENSOR,PROCVR,'cloud_fraction_manual',NEWVAR)
    ENDIF
  ENDFOR

;--------------------------  
; UPDATE DATABASE

  RES = SAVE_DIMITRI_DATABASE(DB_DATA)
  
END