PRO VALIDATE_BRDF

DL = GET_DIMITRI_LOCATION('DL')
OFOLDER = GET_DIMITRI_LOCATION('OUTPUT')
OUTPUT_FOLDER = OFOLDER+DL+'Libya_20110602_REF_MERIS_2nd_Reprocessing'+DL

IB_REGIONS = ['Libya']
IB_REF_SENSORS = ['MERIS']
IB_REF_VERS = ['2nd_Reprocessing']
BRDF_BIN = 5

RES = DIMITRI_INTERFACE_ROUJEAN(OUTPUT_FOLDER,IB_REGIONS,IB_REF_SENSORS,IB_REF_VERS,BRDF_BIN=BRDF_BIN,/VERBOSE)

END